### ISSUE TITLE
stemr package (error in running  the SIR vignettes)

### ISSUE THREAD

**Issue by Yalthoba1407** [fintzij/stemr#10]
I installed stemr package via (install_github("fintzij/stemr") and I ran the SIR vignettes)
I got this error
(
error: Mat::elem(): index out of bounds
Error in pars2parmat(parmat = parmat, pars = param_blocks[[s]]$pars_nat,  : 
  Mat::elem(): index out of bounds
> 
)

**Comment by fintzij** [comment]
Apologies for the delayed response. Thanks for letting me know, it was an object sizing error that prevented saving the mcmc record when the total number of iterations was not a multiple of adaptive MCMC iterations. Just pushed a bug fix.

Thanks for letting me know!
