### ISSUE TITLE
clone stemr 

### ISSUE THREAD

**Issue by Yalthoba1407** [fintzij/stemr#6]
I clone the stemr package, then I got this error 
Error in library(stemr) : there is no package called ‘stemr’
when  I run library(stemr)

**Comment by fintzij** [comment]
Did you build the package after cloning the repo?

Just FYI, the package is currently under active development. We will be merging a pull request that refactors large parts of the package in the next few weeks. This will also affect some user-facing elements, although transitioning to the new version should be fairly straightforward.

**Comment by Yalthoba1407** [comment]
No, I did not. Can you please tell me how can I do that?


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by fintzij** [comment]
It's easiest if you're working in Rstudio. You can just set up a project in the cloned 'stemr' directory and hit install in the build tab. if you've cloned the master branch, make sure you follow the instructions for setting up your toolchain.
